service: labtwin
frameworkVersion: ">=1.52.2 <2.0.0"

provider:
  name: aws
  runtime: python3.8

  stage: staging
  region: eu-central-1

  tracing:
    lambda: true

  logRetentionInDays: 30

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - 'lambda:InvokeFunction'
        - 'lambda:InvokeAsync'
      Resource: "*"
    - Effect: 'Allow'
      Action:
        - 'sts:AssumeRole'
      Resource: '*'
    - Effect: 'Allow'
      Action:
        - 'xray:PutTelemetryRecords'
        - 'xray:PutTraceSegments'
      Resource: '*'

functions:
  cognito_post_confirmation:
    handler: handlers/cognito_post_confirmation.handler
    memorySize: 128
    timeout: 30
plugins:
  - serverless-pseudo-parameters
  - serverless-python-requirements
  - serverless-plugin-log-subscription
