version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      #- restore_cache:
      #    key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      # Create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      # Run linter and tests
      # flake8 --exclude=venv* --statistics
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python3 -m coverage run -m pytest -v
            python3 -m coverage report