version: 2.1
orbs:
  serverless-framework: circleci/serverless-framework@1.0.1

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/python:3-node
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - aws-cli/setup
      - serverless/setup:
        app-name: lambda-functions-experiments
        org-name: circleci
    - run:
        command: serverless deploy -v
        name: deploy