version: 2.1
orbs:
  serverless-framework: circleci/serverless-framework@1.0.1

jobs:
  build:
    executor: serverless/default
    steps:
      - checkout
      - aws-cli/setup
      - serverless/setup:
          app-name: lambda-functions-experiments
          org-name: circleci
      - run:
          command: serverless deploy -v
          name: deploy

orbs:
  aws-cli: circleci/aws-cli@0.2.0
  serverless: circleci/serverless-framework@1.0.1
version: 2.1
workflows:
  build:
    jobs:
      - build